version: "3.7"
services:
  base:
    build:
      context: .
      dockerfile: ./dockerfile
    image: base

  pumpfilter:
    image: base
    container_name: pumpfilter
    depends_on:
      - base
    env_file:
      - ./source/pump2ray_tracker/.env
    restart: unless-stopped
    entrypoint: ["npx", "ts-node", "main.ts"]